name: print-name

on:
  push:
    branches:
      - main

jobs:
  print-name-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print my name
        run: echo "Hello, this is ${{ github.actor }}"

